<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB19rvbm\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB19rvbm/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerB19rvbm.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerB19rvbm\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerB19rvbm\App_KernelProdContainer([
    'container.build_hash' => 'B19rvbm',
    'container.build_id' => 'eb595ac0',
    'container.build_time' => 1642020158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB19rvbm');
