<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgVINbk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgVINbk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJgVINbk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJgVINbk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJgVINbk\App_KernelDevDebugContainer([
    'container.build_hash' => 'JgVINbk',
    'container.build_id' => 'db6ec91f',
    'container.build_time' => 1642020431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgVINbk');
